name: Terraform and Security Scans
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - '.github/workflows/**'
  pull_request:
  schedule:
    - cron: '16 3 * * 3'  # Schedules for tfsec scans

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform Workflow'
    runs-on: ubuntu-latest
    environment: shali-prod
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Information
        run: |
          echo "Current directory: $PWD"
          echo "Contents of current directory:"
          ls -la
          echo "All .tf files in the repository:"
          find . -name "*.tf"
          echo "Git status:"
          git status

      - name: Terraform Init
        run: |
          echo "Running terraform init in directory: $PWD"
          terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Plan
        run: |
          echo "Running terraform plan in directory: $PWD"
          terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform destroy -auto-approve

  tfsec:
    name: 'Run tfsec SARIF Report'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install tfsec
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -O - https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: |
          tfsec --out=tfsec.sarif --format=sarif . || true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec.sarif
