name: Terraform CI/CD Pipeline
on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main
      - 'feature/*'
env:
  TF_VERSION: "1.3.5"
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    name: 'Terraform Workflow'
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: terraform init
      working-directory: .

    - name: Terraform Validate
      run: terraform validate
      working-directory: .

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: .

    - name: Manual Approval
      id: approval
      if: github.ref_name == 'main'
      uses: trstringer/manual-approval@v1
      with:
        approvers: adeolu-rabiu,uzukwujp
        secret: ${{ secrets.GITHUB_TOKEN }}
        minimum-approvals: 1
        issue-title: "Manual approval required for workflow run"
        issue-body: |
          Workflow is pending manual review.
          URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          Required approvers: [Mitchxxx,uzukwujp]
          Respond "approved", "approve", "lgtm", "yes" to continue workflow or "denied", "deny", "no" to cancel.

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && steps.approval.outputs.approved == 'true'
      run: terraform apply -auto-approve tfplan
      working-directory: .
