name: 'Terraform'
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read
jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: production
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: System Information
      run: |
        echo "OS Information:"
        uname -a
        echo "PATH:"
        echo $PATH
        echo "Installed Packages:"
        if command -v apt &> /dev/null; then
          apt list --installed
        elif command -v yum &> /dev/null; then
          yum list installed
        elif command -v brew &> /dev/null; then
          brew list
        else
          echo "Unable to determine package manager"
        fi

    - name: Install unzip
      run: |
        if command -v apt-get &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y unzip
        elif command -v yum &> /dev/null; then
          sudo yum install -y unzip
        elif command -v brew &> /dev/null; then
          brew install unzip
        else
          echo "Unable to install unzip: Unknown package manager"
          exit 1
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
